#include "mainwindow.h"
#include <QtWidgets>
#include <QCryptographicHash>
#include <QJsonArray>
#include <QJsonDocument>
#include <QStandardPaths>
MainWindow::MainWindow(QWidget *parent):QMainWindow(parent),controller(this){buildUi();detectTools();connect(&controller,&AnalysisController::findingReady,this,[this](const Finding &f){addFinding(f);});connect(&controller,&AnalysisController::logMessage,this,[this](const QString &s){console->moveCursor(QTextCursor::End);console->insertPlainText(s);});connect(&controller,&AnalysisController::progressChanged,progress,&QProgressBar::setValue);connect(&controller,&AnalysisController::finished,this,[this](bool cancelled){runButton->setEnabled(true);cancelButton->setEnabled(false);reportButton->setEnabled(!findings.isEmpty());if(cancelled)console->appendPlainText("\nAnalysis cancelled. Partial results retained.");updateSummary();});}
void MainWindow::buildUi(){
 auto *central=new QWidget(this);auto *root=new QVBoxLayout(central);auto *title=new QLabel("Embedded C Static Analyzer — MISRA-oriented Workbench",central);QFont tf=title->font();tf.setPointSize(17);tf.setBold(true);title->setFont(tf);root->addWidget(title);
 auto *projectRow=new QHBoxLayout;projectEdit=new QLineEdit(central);projectEdit->setPlaceholderText("C project or generated STM32 project");auto *open=new QPushButton("Open project...",central);projectRow->addWidget(projectEdit,1);projectRow->addWidget(open);root->addLayout(projectRow);
 auto *options=new QHBoxLayout;standardBox=new QComboBox(central);standardBox->addItems({"c11","c17"});compilerBox=new QCheckBox("Compiler diagnostics",central);compilerBox->setChecked(true);cppcheckBox=new QCheckBox("Cppcheck",central);cppcheckBox->setChecked(true);clangTidyBox=new QCheckBox("Clang-Tidy",central);options->addWidget(new QLabel("Standard:",central));options->addWidget(standardBox);options->addWidget(compilerBox);options->addWidget(cppcheckBox);options->addWidget(clangTidyBox);options->addStretch();root->addLayout(options);
 toolsLabel=new QLabel(central);summaryLabel=new QLabel("Files: 0 | Findings: 0",central);root->addWidget(toolsLabel);root->addWidget(summaryLabel);
 auto *split=new QSplitter(Qt::Horizontal,central);filesTree=new QTreeWidget(split);filesTree->setHeaderLabels({"Analyze","Source file"});filesTree->setMinimumWidth(280);
 tabs=new QTabWidget(split);findingsTable=new QTableWidget(tabs);findingsTable->setColumnCount(8);findingsTable->setHorizontalHeaderLabels({"Severity","Rule","File","Line","Column","Engine","Message","Status"});findingsTable->setSelectionBehavior(QAbstractItemView::SelectRows);findingsTable->setEditTriggers(QAbstractItemView::NoEditTriggers);findingsTable->horizontalHeader()->setStretchLastSection(true);tabs->addTab(findingsTable,"Findings");
 auto *sourcePage=new QWidget(tabs);auto *sourceLayout=new QVBoxLayout(sourcePage);sourceView=new QPlainTextEdit(sourcePage);sourceView->setReadOnly(true);sourceView->setFont(QFontDatabase::systemFont(QFontDatabase::FixedFont));detailsView=new QPlainTextEdit(sourcePage);detailsView->setReadOnly(true);detailsView->setMaximumHeight(150);sourceLayout->addWidget(sourceView,1);sourceLayout->addWidget(detailsView);tabs->addTab(sourcePage,"Source and details");
 console=new QPlainTextEdit(tabs);console->setReadOnly(true);console->setFont(QFontDatabase::systemFont(QFontDatabase::FixedFont));tabs->addTab(console,"Console");split->addWidget(filesTree);split->addWidget(tabs);split->setStretchFactor(1,1);root->addWidget(split,1);
 auto *filterRow=new QHBoxLayout;severityBox=new QComboBox(central);severityBox->addItems({"All severities","Error","Warning","Review","Info"});searchEdit=new QLineEdit(central);searchEdit->setPlaceholderText("Filter findings...");filterRow->addWidget(new QLabel("Filter:",central));filterRow->addWidget(severityBox);filterRow->addWidget(searchEdit,1);root->addLayout(filterRow);
 progress=new QProgressBar(central);root->addWidget(progress);auto *actions=new QHBoxLayout;runButton=new QPushButton("Run analysis",central);cancelButton=new QPushButton("Cancel",central);cancelButton->setEnabled(false);reportButton=new QPushButton("Export JSON + HTML reports...",central);reportButton->setEnabled(false);actions->addWidget(runButton);actions->addWidget(cancelButton);actions->addWidget(reportButton);actions->addStretch();root->addLayout(actions);
 connect(open,&QPushButton::clicked,this,[this]{chooseProject();});connect(runButton,&QPushButton::clicked,this,[this]{runAnalysis();});connect(cancelButton,&QPushButton::clicked,&controller,&AnalysisController::cancel);connect(reportButton,&QPushButton::clicked,this,[this]{generateReports();});connect(findingsTable,&QTableWidget::cellDoubleClicked,this,[this](int row,int){showFinding(row);});connect(severityBox,&QComboBox::currentIndexChanged,this,[this](int){refreshFindings();});connect(searchEdit,&QLineEdit::textChanged,this,[this](const QString &){refreshFindings();});
 setCentralWidget(central);setWindowTitle("Embedded C Static Analyzer v1");resize(1250,850);
}
void MainWindow::chooseProject(){QString d=QFileDialog::getExistingDirectory(this,"Open C project");if(!d.isEmpty()){projectEdit->setText(d);scanProject();}}
void MainWindow::scanProject(){filesTree->clear();QDirIterator it(projectEdit->text(),{"*.c","*.h"},QDir::Files,QDirIterator::Subdirectories);while(it.hasNext()){it.next();if(it.filePath().contains("/build/"))continue;auto *item=new QTreeWidgetItem(filesTree,{"",QDir(projectEdit->text()).relativeFilePath(it.filePath())});item->setCheckState(0,Qt::Checked);item->setData(1,Qt::UserRole,it.filePath());}filesTree->resizeColumnToContents(0);updateSummary();}
QStringList MainWindow::selectedFiles() const{QStringList out;for(int i=0;i<filesTree->topLevelItemCount();++i){auto *item=filesTree->topLevelItem(i);if(item->checkState(0)==Qt::Checked&&item->data(1,Qt::UserRole).toString().endsWith(".c"))out<<item->data(1,Qt::UserRole).toString();}return out;}
QStringList MainWindow::includePaths() const{QStringList out;QDir root(projectEdit->text());for(const QString &p:{"Core/Inc","include","inc","."}){QString path=root.filePath(p);if(QDir(path).exists()&&!out.contains(path))out<<path;}return out;}
void MainWindow::detectTools(){auto state=[](const QString &n){return QStandardPaths::findExecutable(n).isEmpty()?n+": missing":n+": available";};toolsLabel->setText("Tools — "+state("clang")+" | "+state("gcc")+" | "+state("cppcheck")+" | "+state("clang-tidy"));}
void MainWindow::runAnalysis(){if(selectedFiles().isEmpty()){QMessageBox::warning(this,"No files","Select at least one .c file.");return;}findings.clear();refreshFindings();console->clear();runButton->setEnabled(false);cancelButton->setEnabled(true);reportButton->setEnabled(false);controller.start(projectEdit->text(),selectedFiles(),standardBox->currentText(),includePaths(),compilerBox->isChecked(),cppcheckBox->isChecked(),clangTidyBox->isChecked());}
void MainWindow::addFinding(const Finding &f){for(const Finding &old:findings)if(old.fingerprint()==f.fingerprint())return;findings.append(f);refreshFindings();updateSummary();}
void MainWindow::refreshFindings(){findingsTable->setRowCount(0);QString sev=severityBox->currentText();QString text=searchEdit->text();for(const Finding &f:findings){if(sev!="All severities"&&f.severity!=sev)continue;if(!text.isEmpty()&&!f.message.contains(text,Qt::CaseInsensitive)&&!f.rule.contains(text,Qt::CaseInsensitive)&&!f.file.contains(text,Qt::CaseInsensitive))continue;int r=findingsTable->rowCount();findingsTable->insertRow(r);QStringList vals={f.severity,f.rule,QDir(projectEdit->text()).relativeFilePath(f.file),QString::number(f.line),QString::number(f.column),f.engine,f.message,f.status};for(int c=0;c<vals.size();++c)findingsTable->setItem(r,c,new QTableWidgetItem(vals[c]));findingsTable->item(r,0)->setData(Qt::UserRole,f.fingerprint());}findingsTable->resizeColumnsToContents();}
void MainWindow::showFinding(int row){QString fp=findingsTable->item(row,0)->data(Qt::UserRole).toString();for(const Finding &f:findings){if(f.fingerprint()!=fp)continue;QFile file(f.file);if(file.open(QIODevice::ReadOnly|QIODevice::Text)){sourceView->setPlainText(QString::fromUtf8(file.readAll()));QTextCursor cursor(sourceView->document()->findBlockByLineNumber(qMax(0,f.line-1)));sourceView->setTextCursor(cursor);sourceView->centerCursor();}detailsView->setPlainText(QString("Severity: %1\nRule: %2\nEngine: %3\nLocation: %4:%5:%6\n\n%7\n\nReview the finding against your licensed coding standard and project deviation process.").arg(f.severity,f.rule,f.engine,f.file).arg(f.line).arg(f.column).arg(f.message));tabs->setCurrentIndex(1);break;}}
void MainWindow::updateSummary(){int e=0,w=0,r=0;for(const Finding &f:findings){if(f.severity=="Error")++e;else if(f.severity=="Warning")++w;else ++r;}summaryLabel->setText(QString("Selected C files: %1 | Findings: %2 | Errors: %3 | Warnings: %4 | Review: %5").arg(selectedFiles().size()).arg(findings.size()).arg(e).arg(w).arg(r));}
void MainWindow::generateReports(){QString dir=QFileDialog::getExistingDirectory(this,"Select report directory",projectEdit->text());if(dir.isEmpty())return;QJsonArray arr;for(const Finding &f:findings)arr.append(f.toJson());QJsonObject root{{"application","Embedded C Static Analyzer"},{"version","1.0.0"},{"generated",QDateTime::currentDateTime().toString(Qt::ISODate)},{"project",projectEdit->text()},{"c_standard",standardBox->currentText()},{"findings",arr}};QFile json(QDir(dir).filePath("analysis-report.json"));if(json.open(QIODevice::WriteOnly))json.write(QJsonDocument(root).toJson(QJsonDocument::Indented));QString html="<!doctype html><meta charset='utf-8'><title>Embedded C Analysis Report</title><style>body{font-family:sans-serif;max-width:1200px;margin:40px auto}table{border-collapse:collapse;width:100%}td,th{border:1px solid #ccc;padding:8px;text-align:left}.Error{color:#b00020}.Warning{color:#b26a00}.Review{color:#555}</style><h1>Embedded C Analysis Report</h1><p><b>Project:</b> "+projectEdit->text().toHtmlEscaped()+"</p><p><b>Generated:</b> "+QDateTime::currentDateTime().toString(Qt::ISODate)+"</p><table><tr><th>Severity</th><th>Rule</th><th>File</th><th>Location</th><th>Engine</th><th>Message</th></tr>";for(const Finding &f:findings)html+=QString("<tr><td class='%1'>%1</td><td>%2</td><td>%3</td><td>%4:%5</td><td>%6</td><td>%7</td></tr>").arg(f.severity.toHtmlEscaped(),f.rule.toHtmlEscaped(),f.file.toHtmlEscaped()).arg(f.line).arg(f.column).arg(f.engine.toHtmlEscaped(),f.message.toHtmlEscaped());html+="</table><h2>Compliance note</h2><p>This automated report is engineering evidence, not a formal MISRA compliance claim. Review findings, tool configuration, deviations, target assumptions, and hardware tests.</p>";QFile hf(QDir(dir).filePath("analysis-report.html"));if(hf.open(QIODevice::WriteOnly|QIODevice::Text))hf.write(html.toUtf8());QMessageBox::information(this,"Reports generated",QDir(dir).filePath("analysis-report.json")+"\n"+QDir(dir).filePath("analysis-report.html"));}
